// Code generated by protoc-gen-go-enum. DO NOT EDIT.
// source: example/example.proto

package example

// 平台枚举值
const (
	PLATFORM_ANDROID int64 = 1 //Android
	PLATFORM_IOS     int64 = 2 //iOS
)

var (
	PLATFORM_TXT = map[int64]string{
		PLATFORM_ANDROID: "Android",
		PLATFORM_IOS:     "iOS",
	}
)
